extends:
  - 'eslint:recommended'
  - 'xo-space'
  - 'xo-space/esnext'
  - 'xo-space/browser'

ignorePatterns:
  - 'src/scripts/*-vendor/**/*.js'

parserOptions:
  sourceType: module

env:
  browser: true
  commonjs: true
  es2020: true
  node: true
  serviceworker: true
  shared-node-browser: true

# Most of the rules are set to play nicely
# with the prettier-config (but not using
# eslint-config-prettier, which disables too much)
rules:
  capitalized-comments:
    - off
  comma-dangle:
    - error
    - only-multiline
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-mixed-operators:
    - off
  object-curly-spacing:
    - error
    - always
  operator-linebreak:
    - error
    - before
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
