extends:
  - 'eslint:recommended'
  - 'airbnb-base'

ignorePatterns:
  - 'src/scripts/*-vendor/**/*.js'

parserOptions:
  sourceType: module

env:
  browser: true
  commonjs: true
  es2021: true
  node: true
  serviceworker: true
  shared-node-browser: true

# Most of the rules are set to play nicely
# with the prettier-config (but not using
# eslint-config-prettier, which disables too much)
rules:
  arrow-parens:
    - error
    - as-needed
