extends: stylelint-config-sass-guidelines
ignoreFiles: src/styles/3-vendor/**/*.scss

rules:
  max-nesting-depth: 3
  order/order:
    - custom-properties
    - dollar-variables
    - type: at-rule
      hasBlock: false
      name: extend
    - type: at-rule
      hasBlock: false
      name: include
    - declarations
    - rules
  order/properties-alphabetical-order: null
  selector-class-pattern: "^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$"
