extends:
  - stylelint-config-standard-scss
  - stylelint-config-sass-guidelines
ignoreFiles: src/styles/3-vendor/**/*.scss

rules:
  max-nesting-depth: 4
  order/order:
    - custom-properties
    - dollar-variables
    - type: at-rule
      hasBlock: false
      name: extend
    - type: at-rule
      hasBlock: false
      name: include
    - declarations
    - rules
  order/properties-alphabetical-order: null
  selector-class-pattern: "^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$"
  # those rules maybe will become obsolete once we update to native sass
  color-function-notation: 'legacy'
  scss/no-global-function-names: null
  scss/operator-no-unspaced: null
  declaration-empty-line-before: null
  no-descending-specificity: null
  scss/dollar-variable-empty-line-before: null
  alpha-value-notation: null
  max-line-length: 200
  max-empty-lines: 2

