status: wip

# TODO implement multiple sources for different codecs, aka:
# codecs=av01.0.05M.08,opus // codecs=avc1.4D401E,mp4a.40.2

context:
  modifiers: ''
  attributes: 'muted loop playsinline'
  poster: //localhost/__mock/video-landscape.jpg
  source: '//localhost/__mock/video-landscape.mp4'
