status: done

context:
  modifiers: ''
  attributes: 'muted loop playsinline autoplay'
  poster: '//__mock.dev.localhost/video-landscape.jpg'
  sources:
    -
      src: '//__mock.dev.localhost/video-landscape.av1.webm'
      type: 'video/webm; codecs=av01.0.08M.08.0.110.01.01.01.0'
    -
      src: '//__mock.dev.localhost/video-landscape.h264.mp4'
      type: 'video/mp4'
