status: done

context:
  modifiers: ''
  attributes: 'muted loop playsinline autoplay'
  poster: '//__mock.dev.localhost/video-landscape.jpg'
  sources:
    -
      src: '//__mock.dev.localhost/video-landscape.av1.mp4'
      type: 'video/webm; codecs=av01.0.05M.08,opus'
    -
      src: '//__mock.dev.localhost/video-landscape.h264.mp4'
      type: 'video/mp4'
