status: done

context:
  modifiers: ''
  sizes: 100vw
  caption: false
  alt: Alternativtext für das Bild
  sources:
    - width: 480
      src: //via.placeholder.com/480x360
    - width: 960
      src: //via.placeholder.com/960x720
    - width: 1920
      src: //via.placeholder.com/1920x1440
