status: done

context:
  modifiers: ''
  fallback: //picsum.photos/240/160
  alt: Alternativtext für das Bild
  caption: Bildunterschrift
  sources:
    - media: ''
      sizes: 100vw
      srcset: '//picsum.photos/480/320 480w, //picsum.photos/960/640 960w, //picsum.photos/1440/960 1440w'
