status: done

context:
  modifiers: 'image--landscape'
  src: //localhost/__mock/landscape-640.jpg
  alt: Alternativtext für das Bild
  title: Titel des Bildes / Copyrightinfos
  caption: null
  sizes: 100vw
  srcset: '//localhost/__mock/landscape-640.jpg 640w, //localhost/__mock/landscape-960.jpg 960w, //localhost/__mock/landscape-1200.jpg 1200w, //localhost/__mock/landscape-1440.jpg 1440w, //localhost/__mock/landscape-1600.jpg 1600w, //localhost/__mock/landscape-1920.jpg 1920w'

variants:
  - name: portrait
    context:
      modifiers: 'image--portrait'
      src: //localhost/__mock/portrait-640.jpg
      sizes: 100vw
      srcset: '//localhost/__mock/portrait-640.jpg 640w, //localhost/__mock/portrait-960.jpg 960w, //localhost/__mock/portrait-1200.jpg 1200w, //localhost/__mock/portrait-1440.jpg 1440w, //localhost/__mock/portrait-1600.jpg 1600w, //localhost/__mock/portrait-1920.jpg 1920w'
