status: prototype
title: Example Component
tags:
  - tag-one
  - tag-two

context:
  text:
    'Suscipit voluptatibus nobis facere nam accusantium qui. Harum tenetur repudiandae. Nam
    accusamus aliquam.'

variants:
  - name: default
    context:
      modifiers: 'example--default'

  - name: large
    context:
      modifiers: 'example--large'
      text:
        'Repellendus nesciunt nesciunt assumenda. Illo eius cupiditate corrupti. Vel officia ab
        consequatur.'
