status: wip
notes: |
  A button can be an actual button, or a link that should look like
  a button. If you want to use the button as a submit-button you
  should add the attribute `type="submit"` to the button, instead
  of `type="button"`.

context:
  type: button
  label: Button

variants:
  - name: link
    context:
      type: link
      label: Button as link
      href: '#'
      title: Click here!
      modifiers: 'button--link'
