status: wip

context:
  text: '<p>Homepage content and patterns here&hellip;</p>'
  mainImage:
    modifiers: ''
    lazy: true
    fallback: //picsum.photos/240/160
    alt: Alternativtext für das Bild
    title: Titel des Bildes / Copyrightinfos
    caption: Bildunterschrift
    sources:
      - media: ''
        sizes: 100vw
        srcset: '//picsum.photos/480/320 480w, //picsum.photos/960/640 960w, //picsum.photos/1440/960 1440w'
  customImage:
    modifiers: ''
    lazy: true
    fallback: //picsum.photos/320/160
    alt: Alternativtext für das Bild
    title: Titel des Bildes / Copyrightinfos
    caption: Bildunterschrift
    sources:
      - media: ''
        sizes: '(min-width: 960px) 67vw, 100vw',
        srcset: '//picsum.photos/640/320 640w, //picsum.photos/1280/640 1280w, //picsum.photos/1920/960 1920w'
