title: Standard
icon: page
options:
  delete:
    admin: true
    editor: false
  status:
    admin: true
    editor: false

columns:
  left:
    width: 1/1
    sections:
      content:
        type: fields
        fields:
          text: fields/text
  bottom:
    sections:
      seo: sections/seo
