title: Standard-Seite
icon: page

status:
  draft:
    label: Entwurf
    text: Diese Seite ist noch nicht öffentlich
  unlisted:
    label: Versteckte Seite
    text: Die Seite taucht nicht in der Navigation auf, ist aber aufrufbar
  listed:
    label: Öffentliche Seite
    text: Die ist veröffentlicht und Seite taucht in der Navigation auf

columns:
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            extends: fields/text
  - width: 1/3
    sections:
      images:
        type: files
        headline: Bilder
        template: image
        info: "{{ file.dimensions }}"


