title: Benutzer

columns:
  - width: 1/1
    fields:
      firstname:
        label: Vorname
        type: text
        width: 1/2
      lastname:
        label: Nachname
        type: text
        width: 1/2

