title: Dashboard

columns:
  left:
    width: 3/4
    sections:
      home:
        headline: Welcome
        type: info
        text: You can now start coding and building...
  right:
    width: 1/4
    sections:
      pages:
        headline: Alle Seiten
        type: pages
        create: false
        sortable: false
        image: false
  bottom:
    sections:
      seo: sections/seo
